// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request_message.proto

package com.safari.core.protocol;

public final class RequestMessage {
  private RequestMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BizOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.safari.core.protocol.Biz)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string deviceId = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required string deviceId = 1;</code>
     */
    String getDeviceId();
    /**
     * <code>required string deviceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>required string deviceName = 2;</code>
     */
    boolean hasDeviceName();
    /**
     * <code>required string deviceName = 2;</code>
     */
    String getDeviceName();
    /**
     * <code>required string deviceName = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();

    /**
     * <code>required string deviceOs = 3;</code>
     */
    boolean hasDeviceOs();
    /**
     * <code>required string deviceOs = 3;</code>
     */
    String getDeviceOs();
    /**
     * <code>required string deviceOs = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceOsBytes();

    /**
     * <code>required string deviceToken = 4;</code>
     */
    boolean hasDeviceToken();
    /**
     * <code>required string deviceToken = 4;</code>
     */
    String getDeviceToken();
    /**
     * <code>required string deviceToken = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceTokenBytes();

    /**
     * <code>required string deviceType = 5;</code>
     */
    boolean hasDeviceType();
    /**
     * <code>required string deviceType = 5;</code>
     */
    String getDeviceType();
    /**
     * <code>required string deviceType = 5;</code>
     */
    com.google.protobuf.ByteString
        getDeviceTypeBytes();

    /**
     * <code>required string deviceVersion = 6;</code>
     */
    boolean hasDeviceVersion();
    /**
     * <code>required string deviceVersion = 6;</code>
     */
    String getDeviceVersion();
    /**
     * <code>required string deviceVersion = 6;</code>
     */
    com.google.protobuf.ByteString
        getDeviceVersionBytes();

    /**
     * <code>required string netType = 7;</code>
     */
    boolean hasNetType();
    /**
     * <code>required string netType = 7;</code>
     */
    String getNetType();
    /**
     * <code>required string netType = 7;</code>
     */
    com.google.protobuf.ByteString
        getNetTypeBytes();

    /**
     * <code>required string version = 8;</code>
     */
    boolean hasVersion();
    /**
     * <code>required string version = 8;</code>
     */
    String getVersion();
    /**
     * <code>required string version = 8;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>optional string lang = 9;</code>
     */
    boolean hasLang();
    /**
     * <code>optional string lang = 9;</code>
     */
    String getLang();
    /**
     * <code>optional string lang = 9;</code>
     */
    com.google.protobuf.ByteString
        getLangBytes();

    /**
     * <code>optional string token = 10;</code>
     */
    boolean hasToken();
    /**
     * <code>optional string token = 10;</code>
     */
    String getToken();
    /**
     * <code>optional string token = 10;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code com.safari.core.protocol.Biz}
   */
  public  static final class Biz extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.safari.core.protocol.Biz)
      BizOrBuilder {
    // Use Biz.newBuilder() to construct.
    private Biz(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Biz() {
      deviceId_ = "";
      deviceName_ = "";
      deviceOs_ = "";
      deviceToken_ = "";
      deviceType_ = "";
      deviceVersion_ = "";
      netType_ = "";
      version_ = "";
      lang_ = "";
      token_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Biz(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              deviceId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              deviceName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              deviceOs_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              deviceToken_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              deviceType_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              deviceVersion_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              netType_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              version_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              lang_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              token_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestMessage.internal_static_com_safari_core_protocol_Biz_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestMessage.internal_static_com_safari_core_protocol_Biz_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Biz.class, Builder.class);
    }

    private int bitField0_;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile Object deviceId_;
    /**
     * <code>required string deviceId = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string deviceId = 1;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICENAME_FIELD_NUMBER = 2;
    private volatile Object deviceName_;
    /**
     * <code>required string deviceName = 2;</code>
     */
    public boolean hasDeviceName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string deviceName = 2;</code>
     */
    public String getDeviceName() {
      Object ref = deviceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      Object ref = deviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEOS_FIELD_NUMBER = 3;
    private volatile Object deviceOs_;
    /**
     * <code>required string deviceOs = 3;</code>
     */
    public boolean hasDeviceOs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string deviceOs = 3;</code>
     */
    public String getDeviceOs() {
      Object ref = deviceOs_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceOs_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceOs = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceOsBytes() {
      Object ref = deviceOs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceOs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICETOKEN_FIELD_NUMBER = 4;
    private volatile Object deviceToken_;
    /**
     * <code>required string deviceToken = 4;</code>
     */
    public boolean hasDeviceToken() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string deviceToken = 4;</code>
     */
    public String getDeviceToken() {
      Object ref = deviceToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceToken = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTokenBytes() {
      Object ref = deviceToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICETYPE_FIELD_NUMBER = 5;
    private volatile Object deviceType_;
    /**
     * <code>required string deviceType = 5;</code>
     */
    public boolean hasDeviceType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string deviceType = 5;</code>
     */
    public String getDeviceType() {
      Object ref = deviceType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTypeBytes() {
      Object ref = deviceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEVERSION_FIELD_NUMBER = 6;
    private volatile Object deviceVersion_;
    /**
     * <code>required string deviceVersion = 6;</code>
     */
    public boolean hasDeviceVersion() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string deviceVersion = 6;</code>
     */
    public String getDeviceVersion() {
      Object ref = deviceVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceVersion = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceVersionBytes() {
      Object ref = deviceVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NETTYPE_FIELD_NUMBER = 7;
    private volatile Object netType_;
    /**
     * <code>required string netType = 7;</code>
     */
    public boolean hasNetType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string netType = 7;</code>
     */
    public String getNetType() {
      Object ref = netType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          netType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string netType = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNetTypeBytes() {
      Object ref = netType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        netType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 8;
    private volatile Object version_;
    /**
     * <code>required string version = 8;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string version = 8;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string version = 8;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANG_FIELD_NUMBER = 9;
    private volatile Object lang_;
    /**
     * <code>optional string lang = 9;</code>
     */
    public boolean hasLang() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string lang = 9;</code>
     */
    public String getLang() {
      Object ref = lang_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lang_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lang = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLangBytes() {
      Object ref = lang_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 10;
    private volatile Object token_;
    /**
     * <code>optional string token = 10;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string token = 10;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string token = 10;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceOs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, deviceName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, deviceOs_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, deviceToken_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, deviceType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, deviceVersion_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, netType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, version_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, lang_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, token_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, deviceName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, deviceOs_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, deviceToken_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, deviceType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, deviceVersion_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, netType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, version_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, lang_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Biz parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Biz parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Biz parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Biz parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Biz parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static Biz parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static Biz parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static Biz parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static Biz parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static Biz parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Biz prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.safari.core.protocol.Biz}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.safari.core.protocol.Biz)
        BizOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestMessage.internal_static_com_safari_core_protocol_Biz_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestMessage.internal_static_com_safari_core_protocol_Biz_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Biz.class, Builder.class);
      }

      // Construct using com.safari.core.protocol.RequestMessage.Biz.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceOs_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        deviceVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        netType_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        lang_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RequestMessage.internal_static_com_safari_core_protocol_Biz_descriptor;
      }

      public Biz getDefaultInstanceForType() {
        return Biz.getDefaultInstance();
      }

      public Biz build() {
        Biz result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Biz buildPartial() {
        Biz result = new Biz(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceName_ = deviceName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceOs_ = deviceOs_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deviceToken_ = deviceToken_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deviceType_ = deviceType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.deviceVersion_ = deviceVersion_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.netType_ = netType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.lang_ = lang_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Biz) {
          return mergeFrom((Biz)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Biz other) {
        if (other == Biz.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000001;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasDeviceName()) {
          bitField0_ |= 0x00000002;
          deviceName_ = other.deviceName_;
          onChanged();
        }
        if (other.hasDeviceOs()) {
          bitField0_ |= 0x00000004;
          deviceOs_ = other.deviceOs_;
          onChanged();
        }
        if (other.hasDeviceToken()) {
          bitField0_ |= 0x00000008;
          deviceToken_ = other.deviceToken_;
          onChanged();
        }
        if (other.hasDeviceType()) {
          bitField0_ |= 0x00000010;
          deviceType_ = other.deviceType_;
          onChanged();
        }
        if (other.hasDeviceVersion()) {
          bitField0_ |= 0x00000020;
          deviceVersion_ = other.deviceVersion_;
          onChanged();
        }
        if (other.hasNetType()) {
          bitField0_ |= 0x00000040;
          netType_ = other.netType_;
          onChanged();
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000080;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasLang()) {
          bitField0_ |= 0x00000100;
          lang_ = other.lang_;
          onChanged();
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000200;
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          return false;
        }
        if (!hasDeviceName()) {
          return false;
        }
        if (!hasDeviceOs()) {
          return false;
        }
        if (!hasDeviceToken()) {
          return false;
        }
        if (!hasDeviceType()) {
          return false;
        }
        if (!hasDeviceVersion()) {
          return false;
        }
        if (!hasNetType()) {
          return false;
        }
        if (!hasVersion()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Biz parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Biz) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object deviceId_ = "";
      /**
       * <code>required string deviceId = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string deviceId = 1;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string deviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceId = 1;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceId = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceId = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }

      private Object deviceName_ = "";
      /**
       * <code>required string deviceName = 2;</code>
       */
      public boolean hasDeviceName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string deviceName = 2;</code>
       */
      public String getDeviceName() {
        Object ref = deviceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string deviceName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceName = 2;</code>
       */
      public Builder setDeviceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceName = 2;</code>
       */
      public Builder clearDeviceName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceName = 2;</code>
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceName_ = value;
        onChanged();
        return this;
      }

      private Object deviceOs_ = "";
      /**
       * <code>required string deviceOs = 3;</code>
       */
      public boolean hasDeviceOs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string deviceOs = 3;</code>
       */
      public String getDeviceOs() {
        Object ref = deviceOs_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceOs_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string deviceOs = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceOsBytes() {
        Object ref = deviceOs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceOs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceOs = 3;</code>
       */
      public Builder setDeviceOs(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceOs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceOs = 3;</code>
       */
      public Builder clearDeviceOs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceOs_ = getDefaultInstance().getDeviceOs();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceOs = 3;</code>
       */
      public Builder setDeviceOsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceOs_ = value;
        onChanged();
        return this;
      }

      private Object deviceToken_ = "";
      /**
       * <code>required string deviceToken = 4;</code>
       */
      public boolean hasDeviceToken() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string deviceToken = 4;</code>
       */
      public String getDeviceToken() {
        Object ref = deviceToken_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceToken_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string deviceToken = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceTokenBytes() {
        Object ref = deviceToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceToken = 4;</code>
       */
      public Builder setDeviceToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceToken = 4;</code>
       */
      public Builder clearDeviceToken() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceToken_ = getDefaultInstance().getDeviceToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceToken = 4;</code>
       */
      public Builder setDeviceTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceToken_ = value;
        onChanged();
        return this;
      }

      private Object deviceType_ = "";
      /**
       * <code>required string deviceType = 5;</code>
       */
      public boolean hasDeviceType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string deviceType = 5;</code>
       */
      public String getDeviceType() {
        Object ref = deviceType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceType_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string deviceType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceTypeBytes() {
        Object ref = deviceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceType = 5;</code>
       */
      public Builder setDeviceType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceType = 5;</code>
       */
      public Builder clearDeviceType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deviceType_ = getDefaultInstance().getDeviceType();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceType = 5;</code>
       */
      public Builder setDeviceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceType_ = value;
        onChanged();
        return this;
      }

      private Object deviceVersion_ = "";
      /**
       * <code>required string deviceVersion = 6;</code>
       */
      public boolean hasDeviceVersion() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string deviceVersion = 6;</code>
       */
      public String getDeviceVersion() {
        Object ref = deviceVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceVersion_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string deviceVersion = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceVersionBytes() {
        Object ref = deviceVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceVersion = 6;</code>
       */
      public Builder setDeviceVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        deviceVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceVersion = 6;</code>
       */
      public Builder clearDeviceVersion() {
        bitField0_ = (bitField0_ & ~0x00000020);
        deviceVersion_ = getDefaultInstance().getDeviceVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceVersion = 6;</code>
       */
      public Builder setDeviceVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        deviceVersion_ = value;
        onChanged();
        return this;
      }

      private Object netType_ = "";
      /**
       * <code>required string netType = 7;</code>
       */
      public boolean hasNetType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string netType = 7;</code>
       */
      public String getNetType() {
        Object ref = netType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            netType_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string netType = 7;</code>
       */
      public com.google.protobuf.ByteString
          getNetTypeBytes() {
        Object ref = netType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          netType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string netType = 7;</code>
       */
      public Builder setNetType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        netType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string netType = 7;</code>
       */
      public Builder clearNetType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        netType_ = getDefaultInstance().getNetType();
        onChanged();
        return this;
      }
      /**
       * <code>required string netType = 7;</code>
       */
      public Builder setNetTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        netType_ = value;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <code>required string version = 8;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string version = 8;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string version = 8;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string version = 8;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 8;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000080);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 8;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        version_ = value;
        onChanged();
        return this;
      }

      private Object lang_ = "";
      /**
       * <code>optional string lang = 9;</code>
       */
      public boolean hasLang() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string lang = 9;</code>
       */
      public String getLang() {
        Object ref = lang_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lang_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string lang = 9;</code>
       */
      public com.google.protobuf.ByteString
          getLangBytes() {
        Object ref = lang_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          lang_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lang = 9;</code>
       */
      public Builder setLang(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        lang_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lang = 9;</code>
       */
      public Builder clearLang() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lang_ = getDefaultInstance().getLang();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lang = 9;</code>
       */
      public Builder setLangBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        lang_ = value;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <code>optional string token = 10;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string token = 10;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string token = 10;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 10;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 10;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000200);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 10;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        token_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.safari.core.protocol.Biz)
    }

    // @@protoc_insertion_point(class_scope:com.safari.core.protocol.Biz)
    private static final Biz DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Biz();
    }

    public static Biz getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Biz>
        PARSER = new com.google.protobuf.AbstractParser<Biz>() {
      public Biz parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Biz(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Biz> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Biz> getParserForType() {
      return PARSER;
    }

    public Biz getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.safari.core.protocol.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string main = 1;</code>
     */
    boolean hasMain();
    /**
     * <code>optional string main = 1;</code>
     */
    String getMain();
    /**
     * <code>optional string main = 1;</code>
     */
    com.google.protobuf.ByteString
        getMainBytes();

    /**
     * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
     */
    boolean hasBiz();
    /**
     * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
     */
    Biz getBiz();
    /**
     * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
     */
    BizOrBuilder getBizOrBuilder();
  }
  /**
   * Protobuf type {@code com.safari.core.protocol.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.safari.core.protocol.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      main_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              main_ = bs;
              break;
            }
            case 18: {
              Biz.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = biz_.toBuilder();
              }
              biz_ = input.readMessage(Biz.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(biz_);
                biz_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestMessage.internal_static_com_safari_core_protocol_Request_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestMessage.internal_static_com_safari_core_protocol_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Request.class, Builder.class);
    }

    private int bitField0_;
    public static final int MAIN_FIELD_NUMBER = 1;
    private volatile Object main_;
    /**
     * <code>optional string main = 1;</code>
     */
    public boolean hasMain() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string main = 1;</code>
     */
    public String getMain() {
      Object ref = main_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          main_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string main = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMainBytes() {
      Object ref = main_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        main_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIZ_FIELD_NUMBER = 2;
    private Biz biz_;
    /**
     * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
     */
    public boolean hasBiz() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
     */
    public Biz getBiz() {
      return biz_ == null ? Biz.getDefaultInstance() : biz_;
    }
    /**
     * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
     */
    public BizOrBuilder getBizOrBuilder() {
      return biz_ == null ? Biz.getDefaultInstance() : biz_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBiz()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBiz().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, main_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getBiz());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, main_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBiz());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.safari.core.protocol.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.safari.core.protocol.Request)
        RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestMessage.internal_static_com_safari_core_protocol_Request_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestMessage.internal_static_com_safari_core_protocol_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Request.class, Builder.class);
      }

      // Construct using com.safari.core.protocol.RequestMessage.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBizFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        main_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bizBuilder_ == null) {
          biz_ = null;
        } else {
          bizBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RequestMessage.internal_static_com_safari_core_protocol_Request_descriptor;
      }

      public Request getDefaultInstanceForType() {
        return Request.getDefaultInstance();
      }

      public Request build() {
        Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Request buildPartial() {
        Request result = new Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.main_ = main_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (bizBuilder_ == null) {
          result.biz_ = biz_;
        } else {
          result.biz_ = bizBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Request) {
          return mergeFrom((Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Request other) {
        if (other == Request.getDefaultInstance()) return this;
        if (other.hasMain()) {
          bitField0_ |= 0x00000001;
          main_ = other.main_;
          onChanged();
        }
        if (other.hasBiz()) {
          mergeBiz(other.getBiz());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBiz()) {
          return false;
        }
        if (!getBiz().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object main_ = "";
      /**
       * <code>optional string main = 1;</code>
       */
      public boolean hasMain() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string main = 1;</code>
       */
      public String getMain() {
        Object ref = main_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            main_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string main = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMainBytes() {
        Object ref = main_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          main_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string main = 1;</code>
       */
      public Builder setMain(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        main_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string main = 1;</code>
       */
      public Builder clearMain() {
        bitField0_ = (bitField0_ & ~0x00000001);
        main_ = getDefaultInstance().getMain();
        onChanged();
        return this;
      }
      /**
       * <code>optional string main = 1;</code>
       */
      public Builder setMainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        main_ = value;
        onChanged();
        return this;
      }

      private Biz biz_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          Biz, Biz.Builder, BizOrBuilder> bizBuilder_;
      /**
       * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
       */
      public boolean hasBiz() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
       */
      public Biz getBiz() {
        if (bizBuilder_ == null) {
          return biz_ == null ? Biz.getDefaultInstance() : biz_;
        } else {
          return bizBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
       */
      public Builder setBiz(Biz value) {
        if (bizBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          biz_ = value;
          onChanged();
        } else {
          bizBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
       */
      public Builder setBiz(
          Biz.Builder builderForValue) {
        if (bizBuilder_ == null) {
          biz_ = builderForValue.build();
          onChanged();
        } else {
          bizBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
       */
      public Builder mergeBiz(Biz value) {
        if (bizBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              biz_ != null &&
              biz_ != Biz.getDefaultInstance()) {
            biz_ =
              Biz.newBuilder(biz_).mergeFrom(value).buildPartial();
          } else {
            biz_ = value;
          }
          onChanged();
        } else {
          bizBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
       */
      public Builder clearBiz() {
        if (bizBuilder_ == null) {
          biz_ = null;
          onChanged();
        } else {
          bizBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
       */
      public Biz.Builder getBizBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBizFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
       */
      public BizOrBuilder getBizOrBuilder() {
        if (bizBuilder_ != null) {
          return bizBuilder_.getMessageOrBuilder();
        } else {
          return biz_ == null ?
              Biz.getDefaultInstance() : biz_;
        }
      }
      /**
       * <code>required .com.safari.core.protocol.Biz biz = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Biz, Biz.Builder, BizOrBuilder>
          getBizFieldBuilder() {
        if (bizBuilder_ == null) {
          bizBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Biz, Biz.Builder, BizOrBuilder>(
                  getBiz(),
                  getParentForChildren(),
                  isClean());
          biz_ = null;
        }
        return bizBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.safari.core.protocol.Request)
    }

    // @@protoc_insertion_point(class_scope:com.safari.core.protocol.Request)
    private static final Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Request();
    }

    public static Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Request(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_safari_core_protocol_Biz_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_safari_core_protocol_Biz_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_safari_core_protocol_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_safari_core_protocol_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025request_message.proto\022\030com.safari.core" +
      ".protocol\"\274\001\n\003Biz\022\020\n\010deviceId\030\001 \002(\t\022\022\n\nd" +
      "eviceName\030\002 \002(\t\022\020\n\010deviceOs\030\003 \002(\t\022\023\n\013dev" +
      "iceToken\030\004 \002(\t\022\022\n\ndeviceType\030\005 \002(\t\022\025\n\rde" +
      "viceVersion\030\006 \002(\t\022\017\n\007netType\030\007 \002(\t\022\017\n\007ve" +
      "rsion\030\010 \002(\t\022\014\n\004lang\030\t \001(\t\022\r\n\005token\030\n \001(\t" +
      "\"C\n\007Request\022\014\n\004main\030\001 \001(\t\022*\n\003biz\030\002 \002(\0132\035" +
      ".com.safari.core.protocol.BizB*\n\030com.saf" +
      "ari.core.protocolB\016RequestMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_safari_core_protocol_Biz_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_safari_core_protocol_Biz_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_safari_core_protocol_Biz_descriptor,
        new String[] { "DeviceId", "DeviceName", "DeviceOs", "DeviceToken", "DeviceType", "DeviceVersion", "NetType", "Version", "Lang", "Token", });
    internal_static_com_safari_core_protocol_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_safari_core_protocol_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_safari_core_protocol_Request_descriptor,
        new String[] { "Main", "Biz", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
